services:
  todo-fast-api:
    build: .
    container_name: fastapi_todo_app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ${PWD}:/app
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - todo-fastapi-net
    depends_on:
      todo-fastapi-db:
        condition: service_healthy
  todo-fastapi-db:
    image: postgres:18-alpine
    container_name: todo_fastapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - todo-postgres_data:/var/lib/postgresql
    networks:
      - todo-fastapi-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  todo-postgres_data:

networks:
  todo-fastapi-net:
